arm:
  kinematics_solver: "apc_kinematics::APCKinematics"
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: "full"
arm_with_eef:
  kinematics_solver: "apc_kinematics::APCKinematics"
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: "without_roll"
  apc_kinematics_ignore_roll: True
arm_with_eef_orient:
  kinematics_solver: "apc_kinematics::APCKinematics"
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: "full"
  apc_kinematics_ignore_roll: False
